export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AUTH_ERRORS = 'SET_AUTH_ERRORS';
export const SET_LOGIN_ERRORS = 'SET_LOGIN_ERRORS';
export const SET_REGISTER_ERRORS = 'SET_REGISTER_ERRORS';
export const SET_ADD_WORD_ERRORS = 'SET_ADD_WORD_ERRORS';
